config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ('/')
  root 'users#index'
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      post 'login', to: 'login#auth'
      resources :users, only: %i[index show] do
        resources :posts, only: [:index] do
          resources :comments, only: %i[index create]
        end
      end
    end
  end
  # Route to list all users
  # Route to show a specific user
  resources :users, only: %i[index show] do
    # Route to show all posts of a specific user
    # Route to show a specific post of a specific user
    resources :posts, only: %i[index new create show destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  validates :author, presence: true
  validates :post, presence: true
  validates :text, presence: true, length: { maximum: 150 }

  # A method that updates the comments counter for a post.
  def update_comments_counter(id)
    post = Post.find(id)
    counter = post.comments.count
    post.update(comments_counter: counter)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApiController
  before_action :authorize_request

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.order(created_at: :desc)
    render json: @comments
  end

  def create
    @comment = Comment.new(text: params[:comment][:text])
    @comment.author = @current_user
    @comment.post_id = params[:post_id]
    if @comment.save
      render json: @comment, status: :created
    else
      render json: { errors: @comment.errors.full_messages },
             status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
    comment = Comment.new(params.require(:comment).permit(:text))
    comment.author = current_user
    comment.post = @post
    if comment.save
      comment.update_comments_counter(params[:post_id])
      flash[:success] = 'Comment created successfully'
      redirect_to user_post_path(@user.id, @post.id)
    else
      flash.now[:error] = 'Error: Comment could not be created'
      render :_comment, status: :unprocessable_entity, locals: { comment: @comment }
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    respond_to do |f|
      f.html do
        if comment.destroy
          comment.update_comments_counter(params[:post_id])
          flash[:success] = 'Comment deleted successfully'
          redirect_to user_post_path(params[:user_id], params[:post_id])
        else
          flash.now[:error] = 'Error: Comment could not be deleted'
          render :show, status: :unprocessable_entity, locals: { comment: }
        end
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/views/comments/_comment.html.erb
<%= form_with model: Comment, url: user_post_comments_path(@user.id, @post.id), method: :post, local: true do |f| %>
  <div class="comment-new">
    <h3>Add a new Comment:</h3>
    <%= f.label :text, class: "hidden" %>
    <%= f.text_field :text, class: "comment-input" %>
    <%= f.submit "Create Comment", class: "comment-btn btn" %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [post, post.comments.build], local: true) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
  
        <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/comments/new.html.erb
<div class="comments-container">
  <h3>Add new Comment:</h3>
  <%= render 'form', post: @post %>
</div>