config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ('/')
  root 'users#index'
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      post 'login', to: 'login#auth'
      resources :users, only: %i[index show] do
        resources :posts, only: [:index] do
          resources :comments, only: %i[index create]
        end
      end
    end
  end
  # Route to list all users
  # Route to show a specific user
  resources :users, only: %i[index show] do
    # Route to show all posts of a specific user
    # Route to show a specific post of a specific user
    resources :posts, only: %i[index new create show destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy, foreign_key: :post_id
  has_many :likes, dependent: :destroy, foreign_key: :post_id
  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true, length: { maximum: 500 }
  validates :author, presence: true, length: { maximum: 50 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # A method that updates the posts counter for a user.

  def update_posts_counter(user_id)
    user = User.find(user_id)
    counter = user.posts.count
    user.update(posts_counter: counter)
  end

  # A method which returns the 5 most recent comments for a given post.
  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5).reverse
  end
  before_validation :set_defaults

  private

  def set_defaults
    self.likes_counter = 0
    self.comments_counter ||= 0
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  before_action :authorize_request

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.order(created_at: :desc)
    render json: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
    @comments = @post.comments.includes(:author)
  end

  def new
    post = Post.new
    respond_to do |f|
      f.html { render :new, locals: { post: } }
    end
  end

  def create
    post = Post.new(params.require(:post).permit(:title, :text))
    post.author = current_user
    respond_to do |f|
      f.html do
        if post.save
          post.update_posts_counter(current_user.id)
          flash[:success] = 'Post created successfully'
          redirect_to user_posts_path(current_user.id)
        else
          flash.now[:error] = 'Error: Post could not be created'
          render :new, status: :unprocessable_entity, locals: { post: }
        end
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    respond_to do |f|
      f.html do
        if post.destroy
          post.update_posts_counter(params[:user_id])
          flash[:success] = 'Post deleted successfully'
          redirect_to user_posts_path(params[:user_id])
        else
          flash.now[:error] = 'Error: Post could not be deleted'
          render :show, status: :unprocessable_entity, locals: { post: }
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/views/posts/index.html.erb
<%= render 'shared/flashes' %>
<%= render partial: "shared/user", locals: { user: @user } %>
<% @user.posts.each do |post| %>
  <%= link_to user_post_url(id: post.id) do %>
    <div class="post-detailed">
      <div class="post-text">
        <h3><%= post.title %></h3>
        <span class="title-date"><%= post.created_at.strftime('%F %T') %></span>
        <p><%= post.text %></p>
        <div class="user-postdata">
          <p>Comments: <%= post.comments_counter %></p>
          <p>Likes: <%= post.likes_counter %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="comments-container">
    <% counter = 0 %>
    <% post.recent_comments.each do |comment| %>
      <div class="comment">
        <div class="comment-body">
          #<%= counter += 1 %>
          <p class="comment-name"><%= comment.author.name %>:</p>
          <p class="comment-text"><%= comment.text %></p>
        </div>
        <span class="comment-date"><%= comment.created_at.strftime('%F %T') %></span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_with model: post, url: user_posts_path, method: :post, local: true do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <%= f.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
favicon_link_tag(source = "favicon.ico", options = {}) public
<%= render 'shared/flashes' %>
<div class="postdetail-container">
  <div class="postdetail">
    <div class="postdetail-head">
      <h2><%= @post.title %> by <%= @user.name %></h2>
      <span class="title-date"><%= @post.created_at.strftime('%F %T') %></span>
      <div class="postdetail-details">
        <p>Comments: <%= @post.comments_counter %></p>
        <p>Likes: <%= @post.likes_counter%></p>
      </div>
      <div class="delete-post">
        <% if can? :destroy, @post  %>
          <%= button_to "Delete Post", { action: "destroy", id: @post.id },
                                method: :delete, class: 'del-btn btn' %>
        <% end  %>
      </div>
    </div>
    <div class="postdetail-post">
      <p><%= @post.text %></p>
    </div>
  </div>
  <div class="comments-container">
    <% counter = 0 %>
    <% @comments.each do |comment| %>
      <div class="comment">
        <div class="comment-body">
          #<%= counter += 1 %>
          <p class="comment-name"><%= comment.author.name %>:</p>
          <p class="comment-text"><%= comment.text %></p>
        </div>
        <span class="comment-date"><%= comment.created_at.strftime('%F %T') %></span>
        <div class="delete-comment">
          <% if can? :destroy, comment %>
            <%= button_to('Delete Comment', user_post_comment_path(comment.author_id, comment.post_id, comment.id), method: 'delete', id: comment.id, class: 'del-btn btn') %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render partial: "likes/like", locals: { post: @post, user: @user } %>
  <%= render partial: "comments/comment", locals: { post: @post, user: @user } %>
</div>